spring:
  application:
    name: khuropbox
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
cloud:
  aws:
    s3:
      bucket: khuropbox
    credentials:
      access-key:
      secret-key: 
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false